# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginUi3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import res_signup, sys
from db_commands import db_commands

class signup_ui_form(object):
    def handle_sign_up(self):
        c_fname = self.s_Firstname.text()
        c_lname = self.s_Lastname.text()
        c_uname = self.s_User.text()
        c_email = self.s_Email.text()
        c_pass  = self.s_Pass.text()
        c_addr  = self.s_Address.text() + ' ' + self.s_City.text() + ', ' + self.s_State.text() + ' ' + self.s_ZIP.text()

        self.db_cmds.insert_new_customer(c_fname, c_lname, c_uname, c_email, c_pass, c_addr)
        
    def setupUi(self, Form):
        self.db_cmds = db_commands()

        Form.setObjectName("Form")
        Form.resize(625, 565)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 30, 550, 500))
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgba(85, 98, 112, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{\n"
"    color: rgba(131, 96, 53, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(91, 88, 53, 255);\n"
"}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.Image_label = QtWidgets.QLabel(self.widget)
        self.Image_label.setGeometry(QtCore.QRect(40, 30, 231, 431))
        self.Image_label.setStyleSheet("border-image: url(:/images/b3.jpg);\n"
"border-top-left-radius: 50px;")
        self.Image_label.setText("")
        self.Image_label.setObjectName("Image_label")
        self.Gradient = QtWidgets.QLabel(self.widget)
        self.Gradient.setGeometry(QtCore.QRect(40, 30, 231, 431))
        self.Gradient.setStyleSheet("background-color:rgba(0, 0, 0, 80);\n"
"border-top-left-radius: 50px;")
        self.Gradient.setText("")
        self.Gradient.setObjectName("Gradient")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(270, 30, 281, 431))
        self.label_3.setStyleSheet("background-color:rgba(255, 255, 255, 255);\n"
"border-bottom-right-radius: 50px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.Signup_Header = QtWidgets.QLabel(self.widget)
        self.Signup_Header.setGeometry(QtCore.QRect(340, 50, 131, 40))
        font = QtGui.QFont()
        font.setFamily("Ofelia Display")
        font.setPointSize(20)
        font.setBold(True)
        self.Signup_Header.setFont(font)
        self.Signup_Header.setStyleSheet("color:rgba(0, 0, 0, 200);")
        self.Signup_Header.setObjectName("Signup_Header")
        self.s_User = QtWidgets.QLineEdit(self.widget)
        self.s_User.setGeometry(QtCore.QRect(290, 90, 190, 31))
        font = QtGui.QFont()
        font.setFamily("Ofelia Display Medium")
        font.setPointSize(11)
        self.s_User.setFont(font)
        self.s_User.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.s_User.setText("")
        self.s_User.setMaxLength(50)
        self.s_User.setObjectName("s_User")
        self.s_Pass = QtWidgets.QLineEdit(self.widget)
        self.s_Pass.setGeometry(QtCore.QRect(290, 120, 190, 31))
        font = QtGui.QFont()
        font.setFamily("Ofelia Display Medium")
        font.setPointSize(11)
        self.s_Pass.setFont(font)
        self.s_Pass.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.s_Pass.setText("")
        self.s_Pass.setMaxLength(50)
        self.s_Pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.s_Pass.setObjectName("s_Pass")
        self.Button_Signup = QtWidgets.QPushButton(self.widget)
        self.Button_Signup.setGeometry(QtCore.QRect(290, 400, 190, 40))
        font = QtGui.QFont()
        font.setFamily("Ofelia Display")
        font.setPointSize(10)
        font.setBold(True)
        self.Button_Signup.setFont(font)
        self.Button_Signup.setObjectName("Button_Signup")
        self.Button_Signup.clicked.connect(self.handle_sign_up)
        self.s_Firstname = QtWidgets.QLineEdit(self.widget)
        self.s_Firstname.setGeometry(QtCore.QRect(290, 160, 190, 31))
        font = QtGui.QFont()
        font.setFamily("Ofelia Display Medium")
        font.setPointSize(11)
        self.s_Firstname.setFont(font)
        self.s_Firstname.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.s_Firstname.setText("")
        self.s_Firstname.setMaxLength(50)
        self.s_Firstname.setObjectName("s_Firstname")
        self.s_Lastname = QtWidgets.QLineEdit(self.widget)
        self.s_Lastname.setGeometry(QtCore.QRect(290, 200, 190, 31))
        font = QtGui.QFont()
        font.setFamily("Ofelia Display Medium")
        font.setPointSize(11)
        self.s_Lastname.setFont(font)
        self.s_Lastname.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.s_Lastname.setMaxLength(50)
        self.s_Lastname.setObjectName("s_Lastname")
        self.s_Address = QtWidgets.QLineEdit(self.widget)
        self.s_Address.setGeometry(QtCore.QRect(290, 240, 190, 31))
        font = QtGui.QFont()
        font.setFamily("Ofelia Display Medium")
        font.setPointSize(11)
        self.s_Address.setFont(font)
        self.s_Address.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.s_Address.setMaxLength(50)
        self.s_Address.setObjectName("s_Address")
        self.s_City = QtWidgets.QLineEdit(self.widget)
        self.s_City.setGeometry(QtCore.QRect(290, 280, 190, 31))
        font = QtGui.QFont()
        font.setFamily("Ofelia Display Medium")
        font.setPointSize(11)
        self.s_City.setFont(font)
        self.s_City.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.s_City.setText("")
        self.s_City.setMaxLength(50)
        self.s_City.setObjectName("s_City")
        self.s_State = QtWidgets.QLineEdit(self.widget)
        self.s_State.setGeometry(QtCore.QRect(290, 320, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Ofelia Display Medium")
        font.setPointSize(11)
        self.s_State.setFont(font)
        self.s_State.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.s_State.setMaxLength(2)
        self.s_State.setObjectName("s_State")
        self.s_ZIP = QtWidgets.QLineEdit(self.widget)
        self.s_ZIP.setGeometry(QtCore.QRect(410, 320, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Ofelia Display Medium")
        font.setPointSize(11)
        self.s_ZIP.setFont(font)
        self.s_ZIP.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.s_ZIP.setMaxLength(5)
        self.s_ZIP.setObjectName("s_ZIP")
        self.s_Email = QtWidgets.QLineEdit(self.widget)
        self.s_Email.setGeometry(QtCore.QRect(290, 360, 190, 31))
        font = QtGui.QFont()
        font.setFamily("Ofelia Display Medium")
        font.setPointSize(11)
        self.s_Email.setFont(font)
        self.s_Email.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46, 82, 101, 200);\n"
"color:rgba(0, 0, 0, 240);\n"
"padding-bottom:7px;")
        self.s_Email.setText("")
        self.s_Email.setObjectName("s_Email")
        self.Image_label.raise_()
        self.label_3.raise_()
        self.Signup_Header.raise_()
        self.s_User.raise_()
        self.s_Pass.raise_()
        self.Button_Signup.raise_()
        self.s_Firstname.raise_()
        self.s_Lastname.raise_()
        self.s_Address.raise_()
        self.s_City.raise_()
        self.s_State.raise_()
        self.s_ZIP.raise_()
        self.s_Email.raise_()
        self.Gradient.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    
   


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Signup_Header.setText(_translate("Form", "Welcome"))
        self.s_User.setPlaceholderText(_translate("Form", "Username"))
        self.s_Pass.setPlaceholderText(_translate("Form", " Password"))
        self.Button_Signup.setText(_translate("Form", "Sign up!"))
        self.s_Firstname.setPlaceholderText(_translate("Form", "First Name"))
        self.s_Lastname.setPlaceholderText(_translate("Form", "Last Name"))
        self.s_Address.setPlaceholderText(_translate("Form", "Address"))
        self.s_City.setPlaceholderText(_translate("Form", "City"))
        self.s_State.setPlaceholderText(_translate("Form", "State"))
        self.s_ZIP.setPlaceholderText(_translate("Form", "ZIP"))
        self.s_Email.setPlaceholderText(_translate("Form", "Email Address"))

    


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)  # Create the application
    Form = QtWidgets.QWidget()
    ui = signup_ui_form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())



