# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginUi4.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ui_sources.res import res_login 
import sys

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 550)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 30, 370, 480))
        self.widget.setStyleSheet(
            "QPushButton#pushButton{    \n"
            "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop:1 rgba(85, 98, 112, 226));\n"
            "    color:rgba(255, 255, 255, 210);\n"
            "    border-radius:5px;\n"
            "}\n"
            "QPushButton#pushButton:hover{    \n"
            "    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
            "}\n"
            "QPushButton#pushButton:pressed{    \n"
            "    padding-left:5px;\n"
            "    padding-top:5px;\n"
            "    background-color:rgba(105, 118, 132, 200);\n"
            "}\n"
            "\n"
            "QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{    \n"
            "    background-color: rgba(0, 0, 0, 0);\n"
            "    color:rgba(85, 98, 112, 255);\n"
            "}\n"
            "QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{    \n"
            "    color:rgba(155, 168, 182, 220);\n"
            "}\n"
            "QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{    \n"
            "    padding-left:5px;\n"
            "    padding-top:5px;\n"
            "    color:rgba(115, 128, 142, 255);\n"
            "}"
        )
        self.widget.setObjectName("widget")
        self.Back_layer = QtWidgets.QLabel(self.widget)
        self.Back_layer.setGeometry(QtCore.QRect(30, 29, 301, 421))
        self.Back_layer.setStyleSheet(
            "border-image: url(:/images/b2.jpg);\n" "border-radius:20px;"
        )
        self.Back_layer.setText("")
        self.Back_layer.setObjectName("Back_layer")
        self.Back_layer2 = QtWidgets.QLabel(self.widget)
        self.Back_layer2.setGeometry(QtCore.QRect(30, 30, 300, 420))
        self.Back_layer2.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75));\n"
            "border-radius:20px;"
        )
        self.Back_layer2.setText("")
        self.Back_layer2.setObjectName("Back_layer2")
        self.Gradient_Layer = QtWidgets.QLabel(self.widget)
        self.Gradient_Layer.setGeometry(QtCore.QRect(40, 39, 280, 401))
        self.Gradient_Layer.setStyleSheet(
            "background-color:rgba(0, 0, 0, 100);\n" "border-radius:15px;"
        )
        self.Gradient_Layer.setText("")
        self.Gradient_Layer.setAlignment(QtCore.Qt.AlignCenter)
        self.Gradient_Layer.setObjectName("Gradient_Layer")
        self.Header_Label = QtWidgets.QLabel(self.widget)
        self.Header_Label.setGeometry(QtCore.QRect(35, 95, 291, 40))
        font = QtGui.QFont()
        font.setFamily("Ofelia Display Medium")
        font.setPointSize(18)
        font.setBold(False)
        self.Header_Label.setFont(font)
        self.Header_Label.setStyleSheet("color:rgba(255, 255, 255, 210);")
        self.Header_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Header_Label.setObjectName("Header_Label")
        self.lineEdit_User = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_User.setGeometry(QtCore.QRect(80, 165, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Ofelia Display Medium")
        font.setPointSize(10)
        self.lineEdit_User.setFont(font)
        self.lineEdit_User.setStyleSheet(
            "background-color:rgba(0, 0, 0, 0);\n"
            "border:none;\n"
            "border-bottom:2px solid rgba(105, 118, 132, 255);\n"
            "color:rgba(255, 255, 255, 230);\n"
            "padding-bottom:7px;"
        )
        self.lineEdit_User.setObjectName("lineEdit_User")
        self.lineEdit_Password = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Password.setGeometry(QtCore.QRect(80, 230, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Ofelia Display Medium")
        font.setPointSize(10)
        self.lineEdit_Password.setFont(font)
        self.lineEdit_Password.setStyleSheet(
            "background-color:rgba(0, 0, 0, 0);\n"
            "border:none;\n"
            "border-bottom:2px solid rgba(105, 118, 132, 255);\n"
            "color:rgba(255, 255, 255, 230);\n"
            "padding-bottom:7px;"
        )
        self.lineEdit_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(80, 310, 200, 40))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(208, 208, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 65, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(208, 208, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(208, 208, 208))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 47, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 47, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Ofelia Display")
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 340, 301, 61))
        self.label.setStyleSheet("color:rgba(255, 255, 255, 210);")
        font = QtGui.QFont()
        font.setFamily("Ofelia Display Medium")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Back_layer.raise_()
        self.Back_layer2.raise_()
        self.Gradient_Layer.raise_()
        self.pushButton.raise_()
        self.lineEdit_Password.raise_()
        self.lineEdit_User.raise_()
        self.Header_Label.raise_()
        self.label.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Header_Label.setText(_translate("Form", "Meal Variety Prepping"))
        self.lineEdit_User.setPlaceholderText(_translate("Form", "  User Name"))
        self.lineEdit_Password.setPlaceholderText(_translate("Form", "  Password"))
        self.pushButton.setText(_translate("Form", "Log In"))
        self.label.setText(_translate("Form", "Signup"))



# if __name__ == "__main__":
#     app = QtWidgets.QApplication(sys.argv)  # Create the application
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()

#     SignupUi_Form = QtWidgets.QWidget()
#     singup_ui = signup_ui_form()
#     singup_ui.setupUi(SignupUi_Form)


#     sys.exit(app.exec_())






